name: ci
on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      env:
        cache-name: m2
      with:
        path: ~/.m2/repository
        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: |
        mvn --batch-mode package sonar:sonar \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.organization=ccfenner \
          -Dsonar.projectKey=CCFenner_cwa-verification-server
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
    - uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
