name: ci
on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      env:
        cache-name: m2
      with:
        path: ~/.m2/repository
        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn --batch-mode package
    - uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      env:
        cache-name: m2
      with:
        path: ~/.m2/repository
        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/download-artifact@v1
      with:
        name: target
        path: target
    - run: mvn --batch-mode sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ccfenner -Dsonar.projectKey=CCFenner_cwa-verification-server
    
